<div class="listtitlebar">
    <div class="pagetitlebar-title">PASSENDEN WEBSITE\'S</div>
</div>
<div class="listtitlesubbar">
    <div class="webaddressbar">INTERNET ADRESSE</div>
    <div class="bestmatchbar">BEST MATCH</div>
</div>

<form name="build-campaign" action="<?= $this->app_link ?>/campaign/build_campaign" method="post" onsubmit="return check_domain_selected();">
    <input type="hidden" name="campaign_name" value="<?= $campaign_name; ?>"/>
    <input type="hidden" name="keywords" value="<?= $keywords; ?>"/>
    <input type="hidden" name="start_date" value="<?= $start_date; ?>"/>
    <input type="hidden" name="end_date" value="<?= $end_date; ?>"/>
    <?php
    $counter = 0;
    $first = false;
    foreach ($results as $l_no => $link) :
        $counter++;

        // pre-sets:
        $page_url = (strlen($link['PageURL']) > 40) ? $page_url = substr($link['PageURL'], 0, 30) . '...' . substr($link['PageURL'], strlen($link['PageURL']) - 30) : $link['PageURL'];
        $social_shares = $link['fb_shares'] + $link['fb_likes'] + $link['fb_comments'] + $link['tweeter'] + $link['google_plus'];
        $sentimental_type = ($link['sentimental_type'] == 2) ? 'neutral' : ($link['sentimental_type'] == 1) ? 'positive' : 'negative';
        $google_rank = ($link['google_rank'] == '') ? 'n/a' : $link['google_rank'];

        // handle percentage:
        if (!$first) {
            $first = $link['points'];
        }
        $percentage = floor($link['points'] * 100 / $first);

        // big link:
        $big_link_value = $link['PageURL'] . '$%' . $link['DomainURLIDX'] . '$%' . $link['page_id'];
        ?>
        <div class="resultslist">
            <input type="checkbox" name="page_url_checkbox[]" id="page_url_checkbox_<?= $link['page_id']; ?>" class="css-checkbox page_url_checkbox" value="<?= $big_link_value ?>"/>
            <label for="page_url_checkbox_<?= $link['page_id']; ?>" class="css-label"></label>

            <div class="sitelisttitle" title="<?= $link['PageURL']; ?>" style="cursor: help;"><?= $page_url; ?>
            </div>
            <a class="droparrow" data-show-id="site-<?= $link['page_id']; ?>" style="cursor: pointer;"></a>

            <div class="matchrating">
                <div class="matchrating-progress" style="width: <?= $percentage; ?>%"></div>
            </div>

            <a href="#" onclick="getPreviousKeywords(<?= $link['page_id']; ?>)" class="setuplinksbutton" data-reveal-id="setuplinksModal<?= $link['page_id']; ?>" data-animation="none"></a>
        </div>

        <div id="setuplinksModal<?= $link['page_id']; ?>" class="reveal-modal">
            <div class="modal-blueheadline"></div>
            <div class="modal-midline">
                <div class="modal-midlinetext">Wählen Sie alle zutreffenden:</div>
            </div>

            <div class="modal-setuplinksarea">
                <div class="modallistwrap">
                    <div class="modal-setupbox" style="margin-bottom:10px;">
                        <div class="modallisttext" style="margin-top:-14px;line-height:0px;margin-left:0px;">Stichworte For Analytik...</div>
                        <input type="text" id="textbox_keywords_analytics<?= $link['page_id']; ?>" class="modal-setupboxone" name="textbox_keywords_analytics<?= $link['page_id']; ?>">
                    </div>
                    <div class="modal-setupbox" style="margin-bottom:35px;margin-top:15px;">
                        <div class="modallisttext" style="margin-top:-14px;line-height:0px;margin-left:0px;">anchor text...</div>
                        <input type="text" id="textbox_anchor_text<?= $link['page_id']; ?>" class="modal-setupboxone" name="textbox_anchor_text<?= $link['page_id']; ?>">

                    </div>
                    <div class="anchorsuggestion">
                        <div class="anchorsuggestion-title">Letzte Keywörter</div>
                        <ul id="keyword_lists_<?= $link['page_id']; ?>"></ul>
                    </div>

                    <div class="modal-setupbox" style="margin-bottom:35px;">
                        <div class="modallisttext" style="margin-top:-14px;line-height:0px;margin-left:0px;">image url...</div>
                        <input type="text" id="textbox_image_url<?= $link['page_id']; ?>" class="modal-setupboxone" name="textbox_image_url<?= $link['page_id']; ?>">
                    </div>

                    <div class="modal-setupbox" style="margin-bottom:35px;">
                        <div class="modallisttext" style="margin-top:-14px;line-height:0px;margin-left:0px;">myvideo video ID</div>
                        <input type="text" id="textbox_video_url<?= $link['page_id']; ?>" class="modal-setupboxone" name="textbox_video_url<?= $link['page_id']; ?>">
                    </div>
                    <div class="modallisttext">HTML embed</div>
                    <div class="modal-setupbox" style="height:150px;margin-bottom:0px;">
                        <textarea id="textbox_html<?= $link['page_id']; ?> area1" name="textbox_html<?= $link['page_id']; ?>" class="modal-setupboxtwo ckeditor"></textarea>
                    </div>
                </div>
            </div>

            <div class="modal-bottomline">
                <div class="close-reveal-modal modal-savecontent">
                    <div class="modalcheckbox"></div>
                </div>
            </div>
        </div>

        <div id="site-<?= $link['page_id']; ?>" class="dropdownseo" style="display:none;">
            <div class="dropdownbluebg">
                <div class="fulldomainurl">full domain url:</div>
                <div class="sitesactualurl" id="actual_url_<?= $link['page_id']; ?>"> <?= $link['PageURL'] ?></div>
            </div>
            <div class="dropdownpr">
                <div class="dropdownsub-titles">PAGERANK</div>
                <div class="dropdownsub-results"><?= $google_rank; ?></div>
            </div>
            <div class="dropdowncat">
                <div class="dropdownsub-titles">SENTIMENT VALUE</div>
                <div class="dropdownsub-results" id="sentimental_value_<?= $link['page_id']; ?>"><?= $sentimental_type; ?></div>
            </div>
            <div class="dropdownil">
                <div class="dropdownsub-titles">TOTAL BACKLINKS</div>
                <div class="dropdownsub-results"><?= $link['total_back_links']; ?></div>
            </div>
            <div class="dropdowwt" style="width:448px;margin-left:34px;">
                <div class="dropdownsub-titles">SOCIAL SHARES</div>
                <div class="dropdownsub-results"><?= ($social_shares == '') ? 0 : $social_shares; ?></div>
            </div>
            <div class="dropdowol">
                <div class="dropdownsub-titles">OUTGOING LINKS</div>
                <div class="dropdownsub-results"><?= $link['follow_links'] + $link['no_follow_links']; ?></div>
            </div>
        </div>
    <?php
    endforeach;
    foreach ($list_of_domains as $domain_id => $domain):
        ?>
        <input type="hidden" value="<?= $domain; ?>" name="main_domain_url[]"/>
    <?php endforeach; ?>
    <input type="hidden" name="auto_complete_url" value="<?= $auto_complete_url; ?>"/>
    <input type="hidden" name="selected_domain_id" value="<?= $selected_domain_id; ?>"/>
    <input type="hidden" name="total_page_urls" id="total_page_urls" value="<?= $counter; ?>"/>

    <div class="underlistbar"></div>
    <?php
    if ($this->session->get("user-role") !== 'normal') : ?>
        <button class="buildcampbutton" name="buildcampbutton" style="border:none; cursor:pointer"></button>
    <?php endif; ?>
</form>