<?php
$is_admin = false;
if ($this->session->get("user-role") !== "normal") {
    $is_admin = true;
}

$user_domains = $this->session->get("user-domains");
if (!is_array($user_domains)) {
    $user_domains = array();
}
?>
<script type="text/javascript">
    $(document).on('click', '.popup_checkbox', function () {
        if ($(this).is(':checked')) {
            $('#textboxG5').val('').show();
        } else {
            $('#textboxG5').hide();
        }
    });

    function getPreviousKeywords(id) {
        $('#keyword_lists_' + id).html('');
        $('#current_id').val(id);

        $.ajax({
            url: "<?= $this->app_link;?>/campaign/getPreviousKeywords",
            dataType: "json",
            type: "POST",
            data: {
                page_url: $('#actual_url_' + id).text()
            },
            success: function (data) {
                $('#keyword_lists_' + id).html(data.record);
            }
        });
    }

    function setKeywords(id) {
        var current_id = $('#current_id');

        $('#textbox_anchor_text' + current_id.val()).val($('#achor_text_' + id).val());
        $('#textbox_html' + current_id.val()).val($('#html_text_' + id).val());
    }

    /* handle unique selection of 'ziel url' */
    $(document).ready(function () {
        var domain_checkboxs = $('input[id^="domain_checkbox_"]'),
            temp_selector = null;

        domain_checkboxs.on('change', function () {
            var el = $(this);
            if (this.checked) {
                for (var i = 0; i < domain_checkboxs.length; i++) {
                    temp_selector = $(domain_checkboxs[i]);
                    if (temp_selector.attr('id') != el.attr('id')) {
                        temp_selector.attr('checked', false);
                    }
                }
            }
        });

        $("#auto_complete_url").autocomplete({
            source: function (request, response) {
                $("#page_urls_with_id").val('');
                $('#loadmore_div').show();

                $.ajax({
                    url: "<?= $this->app_link;?>/manual_campaign/getAutocomplete",
                    dataType: "json",
                    type: "POST",
                    data: {
                        cat_text: $('#auto_complete_url').val(),
                        domain_id: $('input[name="selected_domain"]:checked').val()
                    },
                    success: function (data) {
                        response(data);
                        $('#loadmore_div').hide();
                    }
                });
            },
            select: function (event, ui) {
                $("#auto_complete_url").val(ui.item.label);
                $("#page_urls_with_id").val(ui.item.id);
            }
        });

        $('#generate_list_form').on('submit', function (ev) {
            ev.preventDefault();

            var formSData = $(this).serialize(), loading = $('#search_loading_div'), resultContent = $('#searched_pages_result');

            if ($('#campaign_name').val() == '') {
                alert("Enter campaign name");
                return false;
            }

            if (!$('input[name="selected_domain"]:checked').length) {
                alert("Select base url");
                return false;
            }

            if ($('#start_date').val() == '') {
                alert("Select Start Date");
                return false;
            }

            if ($('#end_date').val() == '') {
                alert("Select End Date");
                return false;
            }

            if ($('#keywords').val() == '') {
                alert('No keyword to search!');
                return false;
            }

            if ($.trim($('#page_urls_with_id').val()) == "") {
                alert("Please select a page to campaign");
                return false
            }

            resultContent.html('');
            loading.show();

            $.ajax({
                url: "<?= $this->app_link;?>/campaign/search",
                type: "POST",
                data: formSData,
                success: function (data) {
                    try {
                        data = JSON.parse(data);
                    } catch (e) {
                        //
                    }

                    if (data.error !== undefined && data.error) {
                        loading.hide();
                        alert(data.msg);
                        return false;
                    }

                    resultContent.html(data);

                    $('.droparrow').on('click', function () {
                        var show_id = $(this).attr('data-show-id'),
                            content = $('#' + show_id);

                        if (content.css('display') == 'none') {
                            content.css('display', 'block');
                            return false;
                        }

                        content.css('display', 'none');
                        return true;
                    });

                    loading.hide();
                }
            });
        });
    });
</script>
<style>
    .dropdownbox {
        width: 177px;
    }
</style>
<div class="pagetitlebar">
    <div class="pagetitlebar-title">BUILD EINE NEUE KAMPAGNE</div>
    <a href="<?= $this->app_link; ?>/manual_campaign" style="margin-left:343px" class="pagetitlebar-manualbuild">BUILD A HANDBUCH KAMPAGNE</a>

    <div class="buildicon"></div>
</div>
<div class="whitepagewrap">
<?php echo $this->getContent() ?>
<form name="generate_list" id="generate_list_form" action="<?= $this->app_link; ?>/campaign/generate" method="post">
<div class="whitepageblueheader"></div>
<div class="longwhitepagegraybg">
    <input type="text" name="campaign_name" id="campaign_name" class="longwhiteformfield" placeholder="Kampagnen Name" value="<?php echo @$_POST['campaign_name'] ?>">
</div>

<div style="float:left;width:333px;">
    <div class="smallwhitepageblueheader"></div>
    <div class="smallwhitepagegraybg">
        <div class="boxtitle">ZIEL URL</div>
        <a href="#" class="dropdownbox" data-reveal-id="choosedomainModal" data-animation="none">Wählen Sie Domäne <span class="dropdownbox-arrow"></span></a>
    </div>
</div>

<div style="float:right;width:333px;">
    <div class="smallwhitepageblueheader"></div>
    <div class="smallwhitepagegraybg">
        <div class="boxtitle">DOMAIN SEITE</div>
        <!--<a href="#" class="dropdownbox" data-reveal-id="choosepageModal" data-animation="none">Wählen Sie Seite <span class="dropdownbox-arrow"></span></a> !-->
        <input type="text" name="auto_complete_url" id="auto_complete_url" class="autocompleteinputform"/>

        <div id="loadmore_div" style="display: none;" class="loading"></div>
    </div>
</div>

<div style="float:left;width:333px;clear:both;">
    <div class="smallwhitepageblueheader"></div>
    <div class="smallwhitepagegraybg">
        <div class="dropdowncal">
            <input type="hidden" name="end_date" id="end_date" value="">
            <span id="e_date_cal">ENDE DATUM</span>

            <div class="dropdowncal-arrow"></div>
        </div>


        <div class="dropdowncal">
            <input type="hidden" name="start_date" id="start_date" value="">
            <span id="s_date_cal">START DATUM</span>

            <div class="dropdowncal-arrow"></div>
        </div>
    </div>
</div>

<div style="float:right;width:333px;">
    <div class="smallwhitepageblueheader"></div>
    <div class="smallwhitepagegraybg">
        <div class="boxtitle">Seiten pro Domain</div>
        <a href="#" class="dropdownbox" data-reveal-id="choosepages_per_domainModal" data-animation="none">Wählen Sie Seiten pro Domain <span class="dropdownbox-arrow"></span></a>
    </div>
</div>

<div style="float:left;width:333px;">
    <div class="smallwhitepageblueheader"></div>
    <div class="smallwhitepagegraybg">
        <div class="boxtitle">Select algorithm</div>
        <a href="#" class="dropdownbox" data-reveal-id="select_algorithm" data-animation="none"> search algorithm <span class="dropdownbox-arrow"></span></a>
    </div>
</div>

<div style="float:left;width:333px;clear:both;"></div>

<div class="whitepageblueheader"></div>
<div class="longwhitepagegraybg">
    <div id="search_loading_div" style="display: none;" class="loading"></div>
    <input type="text" name="keywords" id="keywords" value="" placeholder="Kampagne erstellen" class="mediumwhiteformfield">
    <button type="submit" class="campaigngeneratelist" name="submit" style="border:none; cursor:pointer;"></button>
</div>

<?php if ($page == "campaign"): ?>
    <!-- choose domain modal window -->
    <div id="choosedomainModal" class="reveal-modal">
        <div class="modal-blueheadline"></div>
        <div class="modal-midline">
            <div class="modal-midlinetext">Wählen Sie Domäne:</div>
        </div>
        <div class="modal-bodyarea">
            <div class="modallistwrap">
                <?php
                $i = 0;
                $list_of_domains = array();
                if (!empty($get_domains)) {
                    foreach ($get_domains as $domain) {
                        if (!in_array($domain->DomainURLIDX, $user_domains) and !$is_admin) {
                            continue;
                        }

                        $list_of_domains[$domain->DomainURLIDX] = $domain->DomainURL;
                        ?>
                        <div class="modal-listbox">
                            <input type="checkbox" name="selected_domain" value="<?= $domain->DomainURLIDX; ?>" id="domain_checkbox_<?= $i; ?>" class="css-checkbox"/>
                            <label for="domain_checkbox_<?= $i; ?>" class="css-label"></label>

                            <div class="modallisttext"><?= $domain->DomainURL; ?></div>
                        </div>
                        <?php $i++;
                    }
                } ?>
                <input type="hidden" name="list_of_domains" id="list_of_domains" value='<?= json_encode($list_of_domains, true); ?>'>
            </div>
        </div>
        <div class="modal-bottomline">
            <div class="close-reveal-modal modal-savecontent">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

    <!-- choose page modal window -->
    <div id="choosepageModal" class="reveal-modal" style="width:818px;left:31%;">
        <div class="modal-blueheadline" style="width:818px;"></div>
        <div class="modal-midline" style="width:818px;">
            <div class="modal-midlinetext">Wählen Sie Seite:</div>
        </div>
        <div class="modal-bodyarea" style="width:750px;">
            <div class="modallistwrap" id="choose_pages_id"></div>
            <!--<div id="loadmore_div"></div>!-->
        </div>
        <div class="modal-bottomline" style="width:818px;">
            <div class="close-reveal-modal modal-savecontent" style="margin-left:361px;">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

    <!-- choose list modal window -->
    <div id="chooselistModal" class="reveal-modal">
        <div class="modal-blueheadline"></div>
        <div class="modal-midline">
            <div class="modal-midlinetext">Wählen Sie Liste:</div>
        </div>
        <div class="modal-bodyarea">
            <div class="modallistwrap">
                <?php if (!empty($get_lists)) {
                    $j = 0;
                    foreach ($get_lists as $list) {
                        ?>
                        <div class="modal-listbox">
                            <input type="checkbox" name="list_checkbox_<?php echo $j; ?>" id="list_checkbox_<?php echo $j; ?>" class="css-checkbox"/>
                            <label for="list_checkbox_<?php echo $j; ?>" class="css-label"></label>

                            <div class="modallisttext"><?php echo $list->Name; ?></div>
                            <input type="hidden" name="list_<?php echo $j; ?>" id="list_<?php echo $j; ?>" value="<?php echo $list->Name; ?>"/>
                        </div>
                        <?php $j++;
                    }
                } ?>
                <input type="hidden" name="total_lists" id="total_lists" value="<?php echo $j; ?>"/>
            </div>
        </div>
        <div class="modal-bottomline">
            <div class="close-reveal-modal modal-savecontent">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

    <!-- choose category modal window -->
    <div id="choosecatModal" class="reveal-modal">
        <div class="modal-blueheadline"></div>
        <div class="modal-midline">
            <div class="modal-midlinetext">Wählen Sie Kategorie:</div>
        </div>
        <div class="modal-bodyarea">
            <div class="modallistwrap" id="choose_categories">
            </div>
        </div>
        <div class="modal-bottomline">
            <div class="close-reveal-modal modal-savecontent">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

    <!-- choose pages per domain modal window -->
    <div id="choosepages_per_domainModal" class="reveal-modal">
        <div class="modal-blueheadline"></div>
        <div class="modal-midline">
            <div class="modal-midlinetext">Wählen Sie Seiten pro Domain:</div>
        </div>
        <div class="modal-bodyarea">
            <?php foreach (array(2, 5, 10, 15) as $k_no => $k) : ?>
                <div class="modallistwrap">
                    <div class="modal-listbox">
                        <input type="radio" name="pages_per_domain" id="pages_per_domain_checkbox_<?= $k; ?>" value="<?= $k; ?>" class="css-checkbox"/>
                        <label for="pages_per_domain_checkbox_<?= $k; ?>" class="css-label"></label>

                        <div class="modallisttext"><?= $k; ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="modal-bottomline">
            <div class="close-reveal-modal modal-savecontent">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

    <div id="select_algorithm" class="reveal-modal">
        <div class="modal-blueheadline"></div>
        <div class="modal-midline">
            <div class="modal-midlinetext">Available search algorithms:</div>
        </div>
        <div class="modal-bodyarea">
            <?php foreach ($algorithms as $algorithm) : ?>
                <div class="modallistwrap">
                    <div class="modal-listbox">
                        <input type="radio" name="algorithm_id" id="algorithm_id_<?= $algorithm->id; ?>" value="<?= $algorithm->id;; ?>" class="css-checkbox"/>
                        <label for="algorithm_id_<?= $algorithm->id;; ?>" class="css-label"></label>

                        <div class="modallisttext"><?= $algorithm->title; ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="modal-bottomline">
            <div class="close-reveal-modal modal-savecontent">
                <div class="modalcheckbox"></div>
            </div>
        </div>
    </div>

<?php endif; ?>

</form>
</div>
<div id="searched_pages_result">
    <div class="listtitlebar" style="border:none;"></div>
</div>
<input type="hidden" id="current_id"/>
<input type="hidden" id="page_urls_with_id"/>