<?php
$is_master = false;
if ($this->session->get("user-role") === 'master') {
    $is_master = true;
}
?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $this->app_link; ?>/css/tab_pages.css"/>

<div class="pagetitlebar">
    <div class="pagetitlebar-title">Crawler Control</div>
</div>

<div class="whitepagewrap" style="margin-top:17px;">
    <div><?= $this->getContent(); ?></div>

    <!-- tabs: -->
    <div id="operations_box" style="height: auto;">
        <div id="tabs_container">
            <ul id="tabs">
                <li id="tab1" onclick='toggle_tabs(this);' class="active"><a>Status</a></li>
                <li id="tab2" onclick='toggle_tabs(this);'><a>Settings</a></li>
            </ul>
        </div>
    </div>

    <!-- tabs content: -->
    <div class="longwhitepagegraybg" style="height:auto;border-top:0;border-top:1px solid #C2C2D3;min-height:50px;padding:10px;">
        <!-- status tab: -->
        <div id="tab1a" class="active_tab_content">
            <div class="importlingwhitewrap" style="width: 100%;padding-bottom: 10px;">
                <?php if (!$is_master) { ?> You don't have access. <?php } else { ?>
                    <table>
                        <tr>
                            <td>Status:</td>
                            <td id="current_status" style="font-weight: bold;"> ---</td>
                        </tr>
                        <tr>
                            <td>Operations:</td>
                            <td>
                                <input type="button" class="operation" value="CheckStatus" data-op="status"> |
                                <input type="button" class="operation" value="Start" data-op="start"> |
                                <input type="button" class="operation" value="Stop" data-op="stop">
                            </td>
                        </tr>
                    </table>
                <?php } ?>
            </div>
        </div>

        <!-- settings tab: -->
        <div id="tab2a" class="hidden_tab_content">
            <div id="tab2f-loading" style="display: none;" class="loading"></div>
            <div class="importlingwhitewrap" style="width: 100%;padding-bottom: 10px;">
                <?php if (!$is_master) { ?> You don't have access. <?php } else { ?>
                    <form id="tab2f" action="<?= $this->app_link; ?>/crawler_control/settings" method="POST">
                        <table>
                            <tr>
                                <td><label for="crawlerPath">Crawler path: </label></td>
                                <td><input type="url" name="crawlerPath" id="crawlerPath" style="width: 160px;text-align: right;" value="<?= isset($crawler_path) ? $crawler_path : ''; ?>"></td>
                            </tr>
                            <tr>
                                <td><label for="atOnce">Links at once: </label></td>
                                <td><input type="text" name="atOnce" id="atOnce" style="width: 40px;text-align: right;" value="<?= isset($crawler_config['atOnce']) ? $crawler_config['atOnce'] : ''; ?>"> / per project</td>
                            </tr>
                            <tr>
                                <td><label for="maxDepth">Max Depth: </label></td>
                                <td><input type="text" name="maxDepth" id="maxDepth" style="width: 40px;text-align: right;" value="<?= isset($crawler_config['maxDepth']) ? $crawler_config['maxDepth'] : ''; ?>"></td>
                            </tr>
                            <tr>
                                <td><label for="user_agent">User Agent:</label></td>
                                <td>
                                    <select name="botName" id="botName" style="width: 160px;">
                                        <option value="-1">- user agent -</option>
                                        <?php
                                        if (count($crawler_agents) > 0) {
                                            $current_agent = isset($crawler_config['botName']) ? $crawler_config['botName'] : 'n/a';
                                            $pattern = '<option value="%s" %s>%s</option>';
                                            $options = array();

                                            foreach ($crawler_agents as $agent) {
                                                $selected = ($current_agent == $agent->name) ? 'selected' : '';
                                                $options[] = sprintf($pattern, $agent->id, $selected, $agent->name);
                                            }

                                            echo implode("\n", $options);
                                        }
                                        ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><input type="submit" value="Save"></td>
                            </tr>
                        </table>
                        <input type="hidden" name="cid" id="cid" value="<?= $config_id; ?>">
                    </form>
                    <div id="tab2f-message" class='tabs-form-msg' style="display: none;"></div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script src="<?= $this->app_link; ?>/js/tab_pages.js"></script>
<script>
    $('#tab2f').on('submit', function (event) {
        event.preventDefault();
        var theForm = $(this), action = theForm.attr('action'), type = theForm.attr('method'), formId = theForm.attr('id'),
            load = $('#' + formId + '-loading'), msg = $('#' + formId + '-message');

        // show loading, hide message (just in case)
        load.show();
        msg.hide().removeClass('tabs-form-msg-ok').removeClass('tabs-form-msg-err');

        $.ajax({
            type: type,
            url: action,
            dataType: 'JSON',
            data: theForm.serialize(),
            success: function (response) {
                var msgClass;

                load.hide();
                msgClass = (response.error) ? 'tabs-form-msg-err' : 'tabs-form-msg-ok';
                msg.html(response.msg).show().addClass(msgClass);

                if (!response.error && response.cid !== undefined) {
                    $('#cid').val(response.cid);
                }
            }
        });
    });

    $('.operation').on('click', function () {
        var clicked = $(this), op = clicked.attr('data-op'), targetMsg = $('#current_status');

        $.ajax({
            type: 'GET',
            url: '<?= $this->app_link;?>/crawler_control/status/' + op,
            dataType: 'JSON',
            success: function (response) {
                if (op != 'status' && response == 'already') {
                    response = op + ': is ' + response;
                }

                targetMsg.html(response).toUpperCase();
            }
        });
    });
</script>